### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by Samasaur1** [Samasaur1/MailKit#3]
MailKit should have a logo

**Comment by richardbmx** [comment]
@Samasaur1  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by Samasaur1** [comment]
@richardbmx Hi Richard! I'd love to have you design a logo for MailKit! The one thing I care about is that it have this format:

![SpriteKit](https://cms-assets.tutsplus.com/uploads/users/769/posts/28785/preview_image/spritekit@2x.jpg)
![SceneKit](https://cms-assets.tutsplus.com/uploads/users/41/posts/25896/preview_image/preview-image@2x.jpg)
![GameplayKit](https://cdn-images-1.medium.com/max/1600/1*ld_ubztErErV3crXxiNjDA.png)

The 3D triple-layer stack with a white top and an image on top, with accent colors below.

Thanks!

**Comment by richardbmx** [comment]
@Samasaur1  perfect what image do you want on the white surface?

**Comment by Samasaur1** [comment]
@richardbmx Probably an envelope like this:
![Envelope](https://upload.wikimedia.org/wikipedia/commons/3/3d/Envelope_font_awesome.svg)
But if you have another idea, that's great too!

**Comment by richardbmx** [comment]
@Samasaur1  perfect I'm going to work on it

**Comment by richardbmx** [comment]
@Samasaur1  Based on what you ask I have designed this for you .. the last layer does not look very good in white therefore I placed lighter shades that match the two deeper layers, the Mail theme is easily represented and is a unique design for your project

![logo107](https://user-images.githubusercontent.com/35604837/46365176-e281ca80-c645-11e8-8483-2ffcf6f0ccf3.png)

**Comment by Samasaur1** [comment]
@richardbmx These look amazing! Thanks so much! I think the logo in shades of purple on a white background is my favorite.

If you could share those with me somehow, that would be great:
- Email: 30577766+Samasaur1@users.noreply.github.com
- Through GitHub: Create a branch and add them as files
- Dropbox link (if you have an account)

Thanks so much for the amazing work!

**Comment by richardbmx** [comment]
@Samasaur1  perfect I'm glad you liked it, I'm going to create a google folder with all the files where you can download them without problem I'll share the link here when I have it

**Comment by richardbmx** [comment]
Here I leave the link with the folder of google drive where are all the necessary files to use the logo and a file of copyright that you seat all the rights on the logo.

If you need something else, I am ready for future projects, I am pleased to know that you liked the logo.

[Google Drive](https://drive.google.com/open?id=1lVUSUdIU0jk5KSjoHZuebaTDrq95Doa0)

**Comment by Samasaur1** [comment]
@richardbmx Thanks so much for the work you did! I'm adding the logo in PR #6, so I can close this issue then.

As for more work, if you want to (don't feel obliged in any way), my project [DiceKit](https://github.com/Samasaur1/DiceKit/) also needs a logo.

**Comment by richardbmx** [comment]
@Samasaur1  perfect I will work in the
